# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: servicemonitor
    app.kubernetes.io/instance: controller-manager-metrics-monitor
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: kepler-operator
    app.kubernetes.io/part-of: kepler-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager-metrics-monitor
  namespace: system
spec:
  endpoints:
    - port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: service
      app.kubernetes.io/part-of: kepler-operator

# spec:
#   endpoints:
#     - path: /metrics
#       port: https
#       scheme: https
#       bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
#       tlsConfig:
#         insecureSkipVerify: true
#   selector:
#     matchLabels:
#       control-plane: controller-manager
