apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: controller-manager-metrics-service
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: kepler-operator
    app.kubernetes.io/part-of: kepler-operator
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager-metrics-service
  namespace: system
spec:
  ports:
  - name: metrics
    port: 8080
    protocol: TCP
    targetPort: metrics
  selector:
      app.kubernetes.io/instance: controller-manager
      app.kubernetes.io/component: manager

# spec:
#   ports:
#   - name: https
#     port: 8443
#     protocol: TCP
#     targetPort: https
#   selector:
#     control-plane: controller-manager
